#define APP_PRIO_TASKS          32u
#define APP_PRIO_STK_SIZE       4096u
#define APP_TASK_START_STK_SIZE 4096u
#define APP_TASK_START_PRIO     1u
#define APP_PRIO_BASE_PRIO      12u
#define APP_PRIO_DELTA_PER_TASK ((OS_CFG_PRIO_MAX - APP_PRIO_BASE_PRIO - 1)/(APP_PRIO_TASKS))
